### ISSUE TITLE
open-replicator-1.0.7.jar is missed in maven repositories

### ISSUE THREAD

**Issue by yaojingguo** [whitesock/open-replicator#5]
Adding the following text to my pom.xml causes "artifact missing" error:
````
<dependency>
        <groupId>open-replicator</groupId>
        <artifactId>open-replicator</artifactId>
        <version>1.0.7</version>
</dependency>
````
Search for "open-replicator" in http://search.maven.org/ returns nothing.

**Comment by osheroff** [comment]
I recently pushed Zendesk's fork of open-replicator to central under com.zendesk.  hope it helps!

**Comment by yaojingguo** [comment]
@osheroff : thanks. I
